version: "2"
services:
  mysql:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 4001:3306
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - MYSQL_DATABASE=test
